### ISSUE TITLE
I can write a query which generates bad sql

### ISSUE THREAD

**Issue by jrwren** [spacemonkeygo/dbx#33]
```
read all (
  select session.id
  join user.pk = session.user_pk
  join associated_account.user_pk = user.pk
  where associated_account.pk = ?
)
```

Generates this SQL, which is not what I intended:

```
SELECT sessions.id FROM users  JOIN sessions ON users.pk = sessions.user_pk  JOIN users ON associated_accounts.user_pk = users.pk WHERE associated_accounts.pk = ?
```

I expect an error guiding me to the "order matters" part of dbx joins.

**Comment by azdagron** [comment]
Thanks for the bug report. We hit this a few months back and completely forgot to file an issue. It took a while for us to notice because we've generally structured the queries like:

    read all (
        select A
        join A.x = B.y
        join B.z = C.q
        where C.p = ?
    )

where the query forms a natural "chain" from one table to the next because he first incarnation of dbx enforced that ordering. The ordering restriction was loosened when we did a major refactor/cleanup. I don't remember why at the moment. Maybe @zeebo remembers?

**Comment by zeebo** [comment]
I do not remember. We should enforce ordering.
